const destaquesData = [
    {
        img: "./images/resma-papel-chamex.webp",
        name: "Resma de Papel Ofício A4",
        brand: 'Chamex',
        type: "papel",
        price: '25.00',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-pilot.jpg",
        name: "Marcador WBM-7 Recarregável",
        brand: 'Pilot',
        type: "marcador-para-quadro-branco",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/tinta-marcador-quadro-500ml.webp",
        name: "Tinta para Marcador de Quadro 500ml",
        brand: 'Radex',
        type: "marcador-para-quadro-branco",
        price: '99.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-vboard.jpg",
        name: "Marcador Vboard Master Recarregável",
        brand: 'Pilot',
        type: "marcador-para-quadro-branco",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/kit-metalico-bic.webp",
        name: "Kit Canetas Metálicas C/3",
        brand: 'Bic',
        type: "canetas",
        price: '29.95',
        falta: false,
    },
]