const destaquesData = [
    {
        img: "./images/resma-papel-chamex.webp",
        name: "Resma de Papel Ofício A4",
        brand: 'Chamex',
        type: "papel-sulfite",
        price: '25.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-adesivo-nexel-50fl.webp",
        name: "Papel Fotográfico Adesivo 130gr 50FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '35.00',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-pilot.jpg",
        name: "Marcador WBM-7 Recarregável",
        brand: 'Pilot',
        type: "marcador-para-quadro-branco",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/papel-foto-nexel-50fl.webp",
        name: "Papel Fotográfico 180gr 50FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '25.00',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-vboard.jpg",
        name: "Marcador Vboard Master Recarregável",
        brand: 'Pilot',
        type: "marcador-para-quadro-branco",
        price: '12.95',
        falta: false,
    },
]