// todos os dados de produtos existentes
const data = [
    //artigos para carimbo
    {
        img: "./images/almofada-para-carimbo-radex.jpg",
        name: "Almofadas Para Carimbo",
        brand: 'Radex',
        type: "carimbo",
        price: '4.95',
        falta: false,
    },
    //artigos para quadro branco
    {
        img: "./images/tinta-marcador-quadro-500ml.webp",
        name: "Tinta para Marcador de Quadro 500ml",
        brand: 'Radex',
        type: "artigos-para-quadro-branco tintas",
        price: '99.95',
        falta: false,
    },
    {
        img: "./images/tinta-marcador-quadro-40ml.webp",
        name: "Tinta para Marcador de Quadro 40ml",
        brand: 'Radex',
        type: "artigos-para-quadro-branco tintas",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-bic-vermelho.webp",
        name: "Marcador para Quadro Branco Marking Vermelho Recarregável",
        brand: 'Bic',
        type: "artigos-para-quadro-branco",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-bic-azul.webp",
        name: "Marcador para Quadro Branco Marking Azul Recarregável",
        brand: 'Bic',
        type: "artigos-para-quadro-branco",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-wbm7-vermelho.webp",
        name: "Marcador para Quadro Branco WBM-7 Recarregável Vermelho",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-wbm7-verde.jpg",
        name: "Marcador para Quadro Branco WBM-7 Recarregável Verde",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-wbm7-preto.webp",
        name: "Marcador para Quadro Branco WBM-7 Recarregável Preto",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-wbm7-azul.webp",
        name: "Marcador para Quadro Branco WBM-7 Recarregável Azul",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-vboard-preto.avif",
        name: "Marcador para Quadro Branco Vboard Master Recarregável Preto",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-vboard-vermelho.webp",
        name: "Marcador para Quadro Branco Vboard Master Recarregável Vermelho",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-vboard-azul.webp",
        name: "Marcador para Quadro Branco Vboard Master Recarregável Azul",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/marcador-quadro-keep.webp",
        name: "Marcador para Quadro Branco Easy Azul",
        brand: 'keep',
        type: "artigos-para-quadro-branco",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/cartucho-vboard-azul.png",
        name: "Cartucho de tinta para Marcador Vboard Master Azul",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/cartucho-vboard-verde.webp",
        name: "Cartucho de tinta para Marcador Vboard Master Verde",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/cartucho-vboard-vermelho.png",
        name: "Cartucho de tinta para Marcador Vboard Master Vermelho",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/cartucho-vboard-preto.png",
        name: "Cartucho de tinta para Marcador Vboard Master Preto",
        brand: 'Pilot',
        type: "artigos-para-quadro-branco",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/apagador-para-quadro-branco.webp",
        name: "Apagador para Quadro Branco Básico Preto",
        brand: 'Radex',
        type: "artigos-para-quadro-branco",
        price: '11.95',
        falta: false,
    },
    {
        img: "./images/apagador-formato-mouse.jpg", 
        name: "Apagador Magnético em Formato de Mouse",
        brand: 'Radex',
        type: "artigos-para-quadro-branco",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/limpador-de-quadro-branco.webp",
        name: "Limpador de Quadro Branco Spray + Flanela",
        brand: 'Radex',
        type: "artigos-para-quadro-branco",
        price: '24.95',
        falta: false,
    },
    //apontadores
    {
        img: "./images/apontador-metal-onda.webp",
        name: "Apontador de Metal",
        brand: 'Onda',
        type: "apontadores",
        price: '1.95',
        falta: false,
    },
    {
        img: "./images/apontador-plástico-pequeno.jpg",
        name: "Apontador Depósito de Plástico",
        brand: 'Onda',
        type: "apontadores",
        price: '3.95',
        falta: true,
    },
    {
        img: "./images/apontador-oval-onda.jpg",
        name: "Apontador Depósito Oval de Plástico",
        brand: 'Onda',
        type: "apontadores",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/apontador-batman.webp",
        name: "Apontador Batman",
        brand: 'Tris',
        type: "apontadores",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/apontador-barbie.webp",
        name: "Apontador Barbie",
        brand: 'Tris',
        type: "apontadores",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/apontador-naruto.webp",
        name: "Apontador Naruto",
        brand: 'Tris',
        type: "apontadores",
        price: '7.95',
        falta: false,
    },
    //blocos e talões
    {
        img: "./images/cartao-de-ponto-tilibra.jpg",
        name: "Cartão de Ponto Mensal RB C/100",
        brand: 'Tilibra',
        type: "blocos-e-impressos",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/vale-com-canhoto-tilibra.webp",
        name: "Vale com Canhoto 50FL",
        brand: 'Tilibra',
        type: "blocos-e-impressos",
        price: '3.00',
        falta: false,
    },
    {
        img: "./images/ficha-pautada-sidgraph.jpg",
        name: "Ficha Pautada 5''x8'' C/100FL",
        brand: 'Sidgraph',
        type: "blocos-e-impressos",
        price: '15.00',
        falta: false,
    },
    {
        img: "./images/carne-gps-tamoio.jpg",
        name: "Guia da Previdência Social Carnê GPS",
        brand: 'Tamoio',
        type: "blocos-e-impressos",
        price: '5.00',
        falta: false,
    },
    {
        img: "./images/recibo-comercial-sem-copia-grafset.jpg",
        name: "Recibo Comercial sem Cópia 1/16",
        brand: 'Grafset',
        type: "blocos-e-impressos",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/nota-promissoria-jandaia.jfif",
        name: "Nota Promissória Amarela 50FL",
        brand: 'Jandaia',
        type: "blocos-e-impressos",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/pedido-com-copia-sidgraph.webp",
        name: "Pedido com Cópia Azul",
        brand: 'Sidgraph',
        type: "blocos-e-impressos",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/bingo-sidgraph.jpg",
        name: "Cartela de Bingo 100FL",
        brand: 'Sidgraph',
        type: "blocos-e-impressos",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/recibo-comercial-tilibra-100fl.webp",
        name: "Recibo Comercial com Canhoto 100FL",
        brand: 'Tilibra',
        type: "blocos-e-impressos",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/recibo-comercial-tilibra-50fl.webp",
        name: "Recibo Comercial com Canhoto 50FL",
        brand: 'Tilibra',
        type: "blocos-e-impressos",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/talao-de-comando-2-corpos-100fl.webp",
        name: "Talão de Comando 2 Corpos 100FL",
        brand: 'Tilibra',
        type: "blocos-e-impressos",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/talao-de-comando-3-corpos-100fl.webp",
        name: "Talão de Comando 3 Corpos 100FL",
        brand: 'Tilibra',
        type: "blocos-e-impressos",
        price: '4.95',
        falta: false,
    },
    //bobinas
    {
        img: "./images/bobina-80-40-48.webp",
        name: "Bobina 80mm x 40m x 48g",
        brand: 'Silfer',
        type: "bobinas",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/bobina-57-22.webp",
        name: "Bobina 57mm x 22m",
        brand: 'Rio branco',
        type: "bobinas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/bobina-57-300-48.webp",
        name: "Bobina 57mm x 300m x 48g",
        brand: 'Rio branco',
        type: "bobinas",
        price: '44.95',
        falta: false,
    },
    {
        img: "./images/bobina-57-30.jpg",
        name: "Bobina 57mm x 30m",
        brand: 'Silfer',
        type: "bobinas",
        price: '3.95',
        falta: false,
    },
    //borrachas
    {
        img: "./images/borracha-redbor.webp",
        name: "Borracha Bicolor AV40",
        brand: 'Red-bor',
        type: "borrachas",
        price: '1.95',
        falta: false,
    },
    {
        img: "./images/borracha-leoeleo.webp",
        name: "Borracha Colorida",
        brand: 'Leo & Leo',
        type: "borrachas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/borracha-bic.webp",
        name: "Borracha Branca com Capa",
        brand: 'Bic',
        type: "borrachas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/borracha-neon-brw.webp",
        name: "Borracha Neon com Capa",
        brand: 'Brw',
        type: "borrachas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/borracha-faber-glitz.webp",
        name: "Borracha Max Glitz",
        brand: 'Fabber-Castell',
        type: "borrachas",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/borracha-maped-shakky.webp",
        name: "Borracha Shakky Bichinhos C/2",
        brand: 'Maped',
        type: "borrachas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/borracha-branca-leoeleo.jpg",
        name: "Borracha branca com Capa Verde",
        brand: 'Leo & Leo',
        type: "borrachas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/borracha-mercur-big.webp",
        name: "Borracha Branca Big com Capa Preta",
        brand: 'Mercur',
        type: "borrachas",
        price: '5.95',
        falta: false,
    },
    //cadernos inteligentes
    {
        img: "./images/caderno-inteligente-dac-preto.jpg",
        name: "Caderno Inteligente Smart All Black 90g",
        brand: 'Dac',
        type: "cadernos-inteligentes",
        price: '79.95',
        falta: false,
    },
    //caligrafia
    {
        img: "./images/aprendendo-a-escrever.webp",
        name: "Livro Aprendendo a Escrever",
        brand: 'Baag',
        type: "caligrafia",
        price: '29.95',
        falta: false,
    },
    {
        img: "./images/amo-meu-abc.webp",
        name: "Livro Eu Amo Meu ABC",
        brand: 'Baag',
        type: "caligrafia",
        price: '5.95',
        falta: false,
    },
    //calculadoras
    {
        img: "./images/calculadora-kk-800a.webp",
        name: "Calculadora KK-800A",
        brand: 'Kenko',
        type: "calculadoras",
        price: '29.95',
        falta: false,
    },
    {
        img: "./images/calculadora-brw.jpg",
        name: "Calculadora Eletrônica de Mesa 12 Dígitos",
        brand: 'Brw',
        type: "calculadoras",
        price: '29.95',
        falta: false,
    },
    {
        img: "./images/calculadora-brw-de-bolso.webp",
        name: "Calculadora de Bolso 8 dígitos",
        brand: 'Brw',
        type: "calculadoras",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/calculadora-elgin-mv4122.jpg",
        name: "Calculadora de mesa MV4122 12 Dígitos",
        brand: 'Elgin',
        type: "calculadoras",
        price: '29.95',
        falta: false,
    },
    {
        img: "./images/calculadora-cientifica-casio.webp",
        name: "Calculadora Científica fx-82ms 2nd Edition",
        brand: 'Casio',
        type: "calculadoras",
        price: '89.95',
        falta: false,
    },
    //canetas-esferograficas
    {
        img: "./images/caneta-magica.jpg",
        name: "Caneta Mágica Tinta Transparente",
        brand: 'Pendente',
        type: "canetas-esferograficas",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/caneta-compactor-economic.png",
        name: "Caneta Esferográfica Economic Azul",
        brand: 'Compactor',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/cores-e-sentimentos-bic.jpg",
        name: "Caneta Colorida Cores e Sentimentos C/10 + Suporte",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/caneta-jet-lux.webp",
        name: "Caneta Esferográfica Jet Lux Colorida",
        brand: 'Compactor',
        type: "canetas-esferograficas",
        price: '2.00',
        falta: false,
    },
    
    {
        img: "./images/caneta-sereia.jpg",
        name: "Caneta Sereia Metalizada",
        brand: 'Pendente',
        type: "canetas-esferograficas",
        price: '5.00',
        falta: false,
    },
    {
        img: "./images/kit-metalico-bic.webp",
        name: "Kit Canetas Esferográficas Metálicas C/3",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '29.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-azul-caixa.webp",
        name: "Caneta Esferográfica Cristal 1.0mm C/50",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '49.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-cristal-azul.webp",
        name: "Caneta Esferográfica Cristal Azul 1.0mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
       {
        img: "./images/caneta-bic-cristal-vermelha.webp",
        name: "Caneta Esferográfica Cristal Vermelha 1.0mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-cristal-preta.webp",
        name: "Caneta Esferográfica Cristal Preta 1.0mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-fine-preta.webp",
        name: "Caneta Esferográfica Fine Preta 0.8mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-fine-azul.webp",
        name: "Caneta Esferográfica Fine Azul 0.8mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-fine-vermelha.webp",
        name: "Caneta Esferográfica Fine Vermelha 0.8mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-compactor-07-vermelha.webp",
        name: "Caneta Esferográfica Vermelha 0.7mm",
        brand: 'Compactor',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-compactor-07-azul.jpg",
        name: "Caneta Esferográfica Azul 0.7mm",
        brand: 'Compactor',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-compactor-07-preta.jpg",
        name: "Caneta Esferográfica Preta 0.7mm",
        brand: 'Compactor',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-fabber-vermelha.webp",
        name: "Caneta Esferográfica Trillux 032 Medium Vermelha 1.0mm",
        brand: 'Fabber-Castell',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-fabber-preta.webp",
        name: "Caneta Esferográfica Trillux 032 Medium Preta 1.0mm",
        brand: 'Fabber-Castell',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-fabber-azul.jpg",
        name: "Caneta Esferográfica Trillux 032 Medium Azul 1.0mm",
        brand: 'Fabber-Castell',
        type: "canetas-esferograficas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-bold-preta.jpg",
        name: "Caneta Esferográfica Bold Intenso Preta 1.6mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-bold-azul.webp",
        name: "Caneta Esferográfica Bold Intenso Azul 1.6mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-bold-vermelha.jpg",
        name: "Caneta Esferográfica Bold Intenso Vermelha 1.6mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-ultrafine-preta.webp",
        name: "Caneta Esferográfica Ultra Fine Preta 0.7mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-ultrafine-vermelha.webp",
        name: "Caneta Esferográfica Ultra Fine Vermelha 0.7mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-ultrafine-azul.jpg",
        name: "Caneta Esferográfica Ultra Fine Azul 0.7mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-bpx-c5.jpg",
        name: "Caneta Esferográfica BPX 0.7mm C/5 Cores",
        brand: 'Cis',
        type: "canetas-esferograficas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/caneta-spiro.webp",
        name: "Caneta Esferográfica Spiro 0.7mm",
        brand: 'Cis',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-spiro-c3.jpg",
        name: "Caneta Esferográfica Spiro 0.7mm C/3 Cores",
        brand: 'Cis',
        type: "canetas-esferograficas",
        price: '11.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bp-1-preta.webp",
        name: "Caneta Esferográfica BP-1 Inox Preta 1.0mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bp-1-vermelha.webp",
        name: "Caneta Esferográfica BP-1 Inox Vermelha 1.0mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bp-1-azul.jpg",
        name: "Caneta Esferográfica BP-1 Inox Azul 1.0mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-4-cores.webp",
        name: "Caneta Esferográfica 4 cores 1.0mm",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '9.95',  
        falta: false,
    },
    {
        img: "./images/caneta-4-cores-capricho.webp",
        name: "Caneta Esferográfica 4 cores Rosa 1.0mm",
        brand: 'Capricho',
        type: "canetas-esferograficas",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/kit-4-canetas-bic-cores.webp",
        name: "Caneta Esferográfica Colorida 1.2mm C/4",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/kit-10-canetas-bic-cores.webp",
        name: "Caneta Esferográfica Colorida 1.2mm C/10",
        brand: 'Bic',
        type: "canetas-esferograficas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bps-07-preta.jpg",
        name: "Caneta Esferográfica BP-S Preta 0.7mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bps-07-azul.jpg",
        name: "Caneta Esferográfica BP-S Azul 0.7mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bps-07-vermelha.jpg",
        name: "Caneta Esferográfica BP-S Vermelha 0.7mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bps-grip-vermelha.jpg",
        name: "Caneta Esferográfica BPS Grip Vermelha 1.0mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bps-grip-preta.jpg",
        name: "Caneta Esferográfica BPS Grip Preta 1.0mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bps-grip-azul.jpg",
        name: "Caneta Esferográfica BPS Grip Azul 1.0mm",
        brand: 'Pilot',
        type: "canetas-esferograficas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/caneta-onda-pro-neon.webp",
        name: "Caneta Esferográfica em Gel Neon",
        brand: 'Onda',
        type: "canetas-esferograficas",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/caneta-3-cores-tenfon.jpg",
        name: "Caneta Esferográfica 3 Cores",
        brand: 'Tenfon',
        type: "canetas-esferograficas",
        price: '5.00',
        falta: false,
    },
    //canetas hidrograficas
    {
        img: "./images/caneta-hidrocor-tons-de-pele-tris.jpg",
        name: "Caneta Hidrocor Mega Hidro Color Tons de Pele C/12 Cores",
        brand: 'Tris',
        type: "canetas-hidrograficas",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/caneta-hidrocor-bazze.jpg",
        name: "Caneta Hidrocor Wave Ponta Fina C/12 Cores",
        brand: 'Bazze',
        type: "canetas-hidrograficas",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/caneta-hidrocor-onda.jpg",
        name: "Caneta Hidrocor Ponta Fina C/12 Cores",
        brand: 'Onda',
        type: "canetas-hidrograficas",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/marcador-fineline-onda-10.jpeg",
        name: "Marcador Fineliner 0.4mm C/10 Cores",
        brand: 'Onda',
        type: "canetas-hidrograficas",
        price: '21.95',
        falta: false,
    },
    {
        img: "./images/marcador-fineline-onda-6.jpg",
        name: "Marcador Fineliner 0.4mm C/6 Cores",
        brand: 'Onda',
        type: "canetas-hidrograficas",
        price: '14.95',
        falta: false,
    },
    //carimbos infantis
    {
        img: "./images/carimbo-infantil-barbie.png",
        name: "Carimbo Infantil Barbie C/4",
        brand: 'Tris',
        type: "carimbos-infantis",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/carimbo-infantil-batman.webp",
        name: "Carimbo Infantil Batman C/4",
        brand: 'Tris',
        type: "carimbos-infantis",
        price: '19.95',
        falta: false,
    },
    //clips
    {
        img: "./images/clips-colorido-epoxi.jpg",
        name: "Clips 5 Aço Epoxi Cores Sortidas C/100",
        brand: 'Acc',
        type: "clips",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/clips-20-ecco-100.webp",
        name: "Clips Galvanizado N°2/0 C/100",
        brand: 'Ecco',
        type: "clips",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/clips-40-acc-50.webp",
        name: "Clips Galvanizado N°4/0 C/50",
        brand: 'Acc',
        type: "clips",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/clips-60-ecco-50.webp",
        name: "Clips Galvanizado N°6/0 C/100",
        brand: 'Ecco',
        type: "clips",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/clips-80-ecco-25.webp",
        name: "Clips Galvanizado N°8/0 C/100",
        brand: 'Ecco',
        type: "clips",
        price: '4.95',
        falta: false,
    },
    //colas
    {
        img: "./images/cola-colorida-caixinha.jpg",
        name: "Cola Colorida 25g C/4 Cores",
        brand: 'Piratininga',
        type: "colas",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/cola-com-glitter-pira.jpg",
        name: "Cola com Glitter 25g C/4 Cores",
        brand: 'Piratininga',
        type: "colas",
        price: '9.95',
        falta: false,
    },  
    {
        img: "./images/cola-com-glitter-radex.jpg",
        name: "Cola com Glitter Heróis 25g C/4 Cores",
        brand: 'Radex',
        type: "colas",
        price: '9.95',
        falta: false,
    },  
    {
        img: "./images/cola-tekbond-793.jpg",
        name: "Cola Instantânea 793 20g",
        brand: 'TekBond',
        type: "colas",
        price: '13.95',
        falta: false,
    },
    {
        img: "./images/cola-tekbond-793.jpg",
        name: "Cola Instantânea 793 20g",
        brand: 'TekBond',
        type: "colas",
        price: '13.95',
        falta: false,
    },
    {
        img: "./images/cola-t6000-tekbond.jpg",
        name: "Cola T6000 para Artesanato 60g",
        brand: 'TekBond',
        type: "colas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/cola-pano-acrilex.webp",
        name: "Cola Pano 35g",
        brand: 'Acrilex',
        type: "colas",
        price: '7.00',
        falta: false,
    },
    {
        img: "./images/cola-branca-koala-500g.jpg",
        name: "Cola Branca 500g",
        brand: 'Koala',
        type: "colas",
        price: '16.95',
        falta: false,
    },
    {
        img: "./images/cola-branca-glinorte-1kg.webp",
        name: "Cola Branca 1kg",
        brand: 'Glinorte',
        type: "colas",
        price: '22.95',
        falta: false,
    },
    {
        img: "./images/brascoplast.webp",
        name: "Cola de Contato Brascoplast 45g",
        brand: 'Brascola',
        type: "colas",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/cola-isopor-pira-80g.png",
        name: "Cola para Isopor Escolar 80g",
        brand: 'Piratininga',
        type: "colas",
        price: '5.95',
        falta: true,
    },
    {
        img: "./images/cola-bastao-scotch-40g.jpg",
        name: "Cola bastão scotch 40g",
        brand: '3M',
        type: "colas",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/cola-bastao-scotch-20g.webp",
        name: "Cola bastão scotch 20g",
        brand: '3M',
        type: "colas",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/cola-bastao-scotch-8g.jpeg",
        name: "Cola bastão scotch 8g",
        brand: '3M',
        type: "colas",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/cola-branca-pira-40g.webp",
        name: "Cola Branca Escolar 40g",
        brand: 'Piratininga',
        type: "colas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/cola-branca-pira-90g.webp",
        name: "Cola Branca Escolar 90g",
        brand: 'Piratininga',
        type: "colas",
        price: '3.95',
        falta: false,
    },
    //cola quente
    {
        img: "./images/pistola-cola-quente-pequena-onda.jpg",
        name: "Pistola Cola Quente Pequena",
        brand: 'Onda',
        type: "cola-quente",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/pistola-cola-quente-grande-onda.jpg",
        name: "Pistola Cola Quente Grande",
        brand: 'Onda',
        type: "cola-quente",
        price: '29.95',
        falta: true,
    },
    {
        img: "./images/cola-quente-grosso.webp",
        name: "Bastão de Cola Quente Grosso",
        brand: 'Nexel',
        type: "cola-quente",
        price: '2.00',
        falta: false,
    },
    {
        img: "./images/cola-quente-fino.jpg",
        name: "Bastão de Cola Quente Fino",
        brand: 'Nexel',
        type: "cola-quente",
        price: '1.00',
        falta: false,
    },
    //compassos
    {
        img: "./images/compasso-tris.jfif",
        name: "Compasso Escolar SU123",
        brand: 'Tris',
        type: "compassos",
        price: '11.95',
        falta: false,
    },
    {
        img: "./images/compasso-onda.webp",
        name: "Compasso Escolar Metal",
        brand: 'Onda',
        type: "compassos",
        price: '9.95',
        falta: false,
    },
    //corretivos
    {
        img: "./images/corretivo-bic-ecolutions.jpg",
        name: "Corretivo Líquido ECOlutions 18ml",
        brand: 'Bic',
        type: "corretivos",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/corretivo-toque-magico.webp",
        name: "Corretivo Líquido 18ml",
        brand: 'Toque mágico',
        type: "corretivos",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/corretivo-fita-masterprint.png",
        name: "Corretivo em Fita MP436 6mx5mm",
        brand: 'Radex',
        type: "corretivos",
        price: '7.95',
        falta: true,
    },
    {
        img: "./images/corretivo-fita-mercur.webp",
        name: "Corretivo em Fita 12mx4,2mm",
        brand: 'Mercur',
        type: "corretivos",
        price: '17.95',
        falta: false,
    },
    {
        img: "./images/corretivo-fita-onda.webp",
        name: "Corretivo em Fita 6mx5mm",
        brand: 'Onda',
        type: "corretivos",
        price: '9.95    ',
        falta: false,
    },
    {
        img: "./images/caneta-corretiva-radex.webp",
        name: "Caneta Corretiva",
        brand: 'Radex',
        type: "corretivos",
        price: '9.95',
        falta: false,
    },
    //dicionários
    {
        img: "./images/meu-primeiro-livro-ingles.webp",
        name: "Meu Primeiro Livro para Aprender Inglês",
        brand: 'Todolivro',
        type: "dicionarios",
        price: '39.95',
        falta: false,
    },
    {
        img: "./images/dicionario-silveira-bueno.jpg",
        name: "Dicionário Escolar Silveira Bueno",
        brand: 'Global',
        type: "dicionarios",
        price: '39.95',
        falta: false,
    },
    {
        img: "./images/mini-dicionario-espanhol-scottini.webp",
        name: "Minidicionário Scottini Espanhol",
        brand: 'Todolivro',
        type: "dicionarios",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/mini-dicionario-portugues-scottini.webp",
        name: "Minidicionário Scottini Língua Portuguesa",
        brand: 'Todolivro',
        type: "dicionarios",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/mini-dicionario-ingles-scottini.webp",
        name: "Minidicionário Scottini Inglês",
        brand: 'Todolivro',
        type: "dicionarios",
        price: '9.95',
        falta: false,
    },
    //elásticos
    {
        img: "./images/elastico-mercur-100.jpg",
        name: "Elásticos Amarelos Super C/100",
        brand: 'Mercur',
        type: "elasticos",
        price: '9.95',
        falta: false,
    },  
    {
        img: "./images/elastico-redbor-60.jpg",
        name: "Elásticos Amarelos C/60",
        brand: 'Redbor',
        type: "elasticos",
        price: '3.95',
        falta: false,
    },  
    {
        img: "./images/elastico-mercur-60.jpg",
        name: "Elásticos Amarelos Standard C/60",
        brand: 'Mercur',
        type: "elasticos",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/elastico-mercur-120.webp",
        name: "Elásticos Amarelos Standard C/120",
        brand: 'Mercur',
        type: "elasticos",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/elastico-mercur-1200.jpg",
        name: "Elásticos Amarelos Super C/1200",
        brand: 'Mercur',
        type: "elasticos",
        price: '59.95',
        falta: false,
    },
    {
        img: "./images/elastico-mercur-2200.jpg",
        name: "Elásticos Amarelos Super C/2200",
        brand: 'Mercur',
        type: "elasticos",
        price: '99.95',
        falta: false,
    },
    //emborrachados
    {
        img: "./images/emborrachado-tapete.webp",
        name: "Folha de Emborrachado/EVA Peças",
        brand: 'Ibel',
        type: "emborrachados",
        price: '49.95',
        falta: false,
    },
    {
        img: "./images/emborrachado-estampado.webp",
        name: "Folha de Emborrachado/EVA Estampado 40x48cm",
        brand: 'Ibel',
        type: "emborrachados",
        price: '7.00',
        falta: false,
    },
    {
        img: "./images/eva-liso.webp",
        name: "Folha de Emborrachado/EVA Liso 40x48cm",
        brand: 'Ibel',
        type: "emborrachados",
        price: '3.00',
        falta: false,
    },
    {
        img: "./images/eva-com-glitter.webp",
        name: "Folha de Emborrachado/EVA com Glitter 40x48cm",
        brand: 'Ibel',
        type: "emborrachados",
        price: '7.00',
        falta: false,
    },
    //envelopes
    {
        img: "./images/envelope-sko34.webp",
        name: "Envelope Ouro 80g SKO 34",
        brand: 'Scrity',
        type: "envelopes",
        price: '0.75',
        falta: false,
    },
    {
        img: "./images/envelope-skn34.webp",
        name: "Envelope Kraft 80g SKN 34",
        brand: 'Scrity',
        type: "envelopes",
        price: '0.75',
        falta: false,
    },
    {
        img: "./images/envelope-sof34.webp",
        name: "Envelope Branco 80g SOF 34",
        brand: 'Scrity',
        type: "envelopes",
        price: '0.75',
        falta: false,
    },
    //escritorio
    {
        img: "./images/extrator-chaparrau.jpg",
        name: "Extrator de Grampos Aço Inoxidável",
        brand: 'chaparrau',
        type: "extrator",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/espeto-para-papel.webp",
        name: "Espeto para Papel",
        brand: 'ACC',
        type: "escritorio",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/perfurador-alicate-brw.webp",
        name: "Perfurador de Papel Alicate Metálico",
        brand: 'Brw',
        type: "escritorio",
        price: '14.95',
        falta: false,
    },
    //estiletes
    {
        img: "./images/estilete-plastico-onda.webp",
        name: "Estilete Plástico Largo",
        brand: 'Onda',
        type: "estiletes",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/estilete-de-metal-sq.jpg",
        name: "Estilete de Metal Largo 15cm",
        brand: 'Sq',
        type: "estiletes",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/estilete-de-metal-leoarte.png",
        name: "Estilete de Metal Largo Lâmina de 18mm",
        brand: 'Leoarte',
        type: "estiletes",
        price: '12.95',
        falta: false,
    },
    //etiquetas
    {
        img: "./images/etiquetas-princesas.jpg",
        name: "Etiqueta Escolar Adesiva Princesas C/8",
        brand: 'Tilibra',
        type: "etiquetas",
        price: '4.95',
        falta: false,
    },
    //fitas 
        {
        img: "./images/fita-isolante-adelbras.webp",
        name: "Fita Isolante Anti-chama 19mmx5m",
        brand: 'Adelbras',
        type: "fitas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/fita-tartan.webp",
        name: "Fita Tartan 45mmx50m",
        brand: '3M',
        type: "fitas",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/fita-3m-tr.webp",
        name: "Fita Adesiva Transparente 45mmx45m",
        brand: '3M',
        type: "fitas",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/fita-nexel.jpeg",
        name: "Fita Adesiva Transparente 45mmx45m",
        brand: 'Nexel',
        type: "fitas",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/fita-fixa-forte-12mm.webp",
        name: "Fita Dupla Face Fixa Forte 12mmx2m",
        brand: '3M',
        type: "fitas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/fita-fixa-forte-19mm.jpg",
        name: "Fita Dupla Face Fixa Forte 19mmx2m",
        brand: 'Nexel',
        type: "fitas",
        price: '24.95',
        falta: false,
    },
    //giz de cera
    {
        img: "./images/giz-de-cera-koala.jpg",
        name: "Giz de Cera C/12 Cores",
        brand: 'Koala',
        type: "giz-de-cera",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/baby-giz-koala.webp",
        name: "Giz de Cera Super Grosso C/7 Cores",
        brand: 'Koala',
        type: "giz-de-cera",
        price: '17.95',
        falta: false,
    },
    {
        img: "./images/giz-de-cera-pira.jpg",
        name: "Giz de Cera C/12 Cores",
        brand: 'Piratininga',
        type: "giz-de-cera",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/giz-de-cera-onda.webp",
        name: "Giz de Cera C/12 Cores",
        brand: 'Onda',
        type: "giz-de-cera",
        price: '6.95',
        falta: false,
    },
    //giz-escolar
    {
        img: "./images/giz-escolar-branco.webp",
        name: "Giz Escolar Branco",
        brand: 'Delta',
        type: "giz-escolar",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/giz-escolar-colorido.jfif",
        name: "Giz Escolar Colorido",
        brand: 'Delta',
        type: "giz-escolar",
        price: '5.95',
        falta: false,
    },
    //grampeadores
    {
        img: "./images/grampeador-master.webp",
        name: "Grampeador Master 100FL",
        brand: 'Jocar Office',
        type: "grampeadores",
        price: '129.95',
        falta: false,
    },
    {
        img: "./images/grampeador-maped-a17.jpg",
        name: "Grampeador de Mesa Preto A17",
        brand: 'Maped',
        type: "grampeadores",
        price: '34.95',
        falta: false,
    },
    {
        img: "./images/grampeador-tapeceiro.webp",
        name: "Grampeador para Tapeceiro 4-14mm",
        brand: 'Western',
        type: "grampeadores",
        price: '69.95',
        falta: true,
    },
    //grampos
    {
        img: "./images/grampo-2313.jpg",
        name: "Grampos 23/13 C/1000",
        brand: 'Acc',
        type: "grampos",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/grampo-frama.webp",
        name: "Grampos 26/6 C/5000",
        brand: 'Frama',
        type: "grampos",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/grampo-onda.webp",
        name: "Grampos 26/6 C/5000",
        brand: 'Onda',
        type: "grampos",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/grampo-masterprint.webp",
        name: "Grampos 26/6 C/5000",
        brand: 'Masterprint',
        type: "grampos",
        price: '9.95',
        falta: false,
    },
    //informática
    {
        img: "./images/fone-de-ouvido-philips.jpeg",
        name: "Fone de Ouvido Headset com Fio 2000 Series",
        brand: 'Philips',
        type: "informatica",
        price: '99.95',
        falta: false,
    },
    {
        img: "./images/teclado-multilaser.webp",
        name: "Teclado Básico com Fio USB",
        brand: 'Multilaser',
        type: "informatica",
        price: '49.95',
        falta: false,
    },
    {
        img: "./images/mouse-com-fio.webp",
        name: "Mouse Óptico com Fio 1200dpi",
        brand: 'Multilaser',
        type: "informatica",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/mouse-sem-fio.webp",
        name: "Mouse Sem Fio 1200dpi",
        brand: 'Multilaser',
        type: "informatica",
        price: '39.95',
        falta: false,
    },
    {
        img: "./images/mouse-pad-multilaser-slim.webp",
        name: "Mouse Pad Slim",
        brand: 'Multilaser',
        type: "informatica",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/mouse-pad-multilaser-ergonomico.webp",
        name: "Mouse pad Ergonômico com Apoio Gel",
        brand: 'Multilaser',
        type: "informatica",
        price: '39.95',
        falta: false,
    },
    {
        img: "./images/caixa-de-som-multilaser.jpg",
        name: "Caixa de Som Multimídia 3WRMS",
        brand: 'Multilaser',
        type: "informatica",
        price: '39.95',
        falta: false,
    },
    //lápis
    {
        img: "./images/lapis-spiro.jpg",
        name: "Lápis Grafite Spiro com Borracha C/4",
        brand: 'Cis',
        type: "lapis-comum",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/lapis-tabuada-bazze.png",
        name: "Lápis Grafite Tabuada",
        brand: 'Bazze',
        type: "lapis-comum",
        price: '1.95',
        falta: false,
    },
        {
        img: "./images/lapis-grafite-princesa.webp",
        name: "Lápis Preto Princesa",
        brand: 'Tris',
        type: "lapis-comum",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/lapis-grafite-batman.jpg",
        name: "Lápis Preto Batman",
        brand: 'Tris',
        type: "lapis-comum",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/lapis-serelepe.jpg",
        name: "Lápis Preto N2",
        brand: 'Serelepe',
        type: "lapis-comum",
        price: '0.75',
        falta: false,
    },
    {
        img: "./images/lapis-serelepe-caixa.webp",
        name: "Caixa de Lápis Preto N2 C/144",
        brand: 'Serelepe',
        type: "lapis-comum",
        price: '59.95',
        falta: false,
    },
    {
        img: "./images/lapis-onda-caixa.webp",
        name: "Caixa de Lápis Preto N2 C/144",
        brand: 'onda',
        type: "lapis-comum",
        price: '59.95',
        falta: false,
    },
    {
        img: "./images/lapis-bic-evolution.jpg",
        name: "Lápis Preto Evolution HB2",
        brand: 'Bic',
        type: "lapis-comum",
        price: '1.00',
        falta: false,
    },
    //lapis de cor
        {
        img: "./images/lapis-de-cor-faber-castell.webp",
        name: "Ecolápis de Cor Sextavado C/36",
        brand: 'Faber-Castell',
        type: "lapis-de-cor",
        price: '69.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-naruto.jfif",
        name: "Lápis de Cor Naruto Shippudden C/12",
        brand: 'Viz',
        type: "lapis-de-cor",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-barbie.webp",
        name: "Lápis de Cor Barbie C/12",
        brand: 'Tris',
        type: "lapis-de-cor",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-batman.webp",
        name: "Lápis de Cor Batman C/12",
        brand: 'Tris',
        type: "lapis-de-cor",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-tons-de-pele-tris.webp",
        name: "Lápis de Cor Tons de Pele C/12",
        brand: 'Tris',
        type: "lapis-de-cor",
        price: '17.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-serelepe.webp",
        name: "Lápis de Cor C/12",
        brand: 'Serelepe',
        type: "lapis-de-cor",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-onda-12.webp",
        name: "Lápis de Cor Sextavado C/12",
        brand: 'Onda',
        type: "lapis-de-cor",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-leo&leo.webp",
        name: "Lápis de Cor Redondo C/12",
        brand: 'Leo&Leo',
        type: "lapis-de-cor",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-onda-24.jpg",
        name: "Lápis de Cor Redondo C/24",
        brand: 'Onda',
        type: "lapis-de-cor",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/lapis-de-cor-onda-big.webp",
        name: "Lápis de Cor BIG triangular C/12",
        brand: 'Onda',
        type: "lapis-de-cor",
        price: '19.95',
        falta: false,
    },
    //lapiseiras
    {
        img: "./images/lapiseira-dreamy.webp",
        name: "Lapiseira Holic Dreamy 0.7mm Cores",
        brand: 'Tris',
        type: "lapiseiras",
        price: '15.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-pentel-05-branca.jpg",
        name: "Lapiseira Profissional Sharp P205 0.5mm Branca",
        brand: 'Pentel',
        type: "lapiseiras",
        price: '34.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-pentel-09-branca.jpg",
        name: "Lapiseira Profissional Sharp P209 0.9mm Branca",
        brand: 'Pentel',
        type: "lapiseiras",
        price: '34.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-pentel-07-verde-neon.png",
        name: "Lapiseira Profissional Sharp Collection P207 0.7mm Neon",
        brand: 'Pentel',
        type: "lapiseiras",
        price: '34.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-onda-07.webp",
        name: "Lapiseira de Metal 0.7mm Azul",
        brand: 'Onda',
        type: "lapiseiras",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-onda-05.webp",
        name: "Lapiseira de Metal 0.5mm Preta",
        brand: 'Onda',
        type: "lapiseiras",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-onda-09.webp",
        name: "Lapiseira de Metal 0.9mm Preta",
        brand: 'Onda',
        type: "lapiseiras",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-juice-keep-07.webp",
        name: "Lapiseira Plástica Juice 0.7mm Cores",
        brand: 'Keep',
        type: "lapiseiras",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/lapiseira-tris-college-20.webp",
        name: "Lapiseira College 2.0mm",
        brand: 'Tris',
        type: "lapiseiras",
        price: '7.95',
        falta: true,
    },
    //marca-textos
    {
        img: "./images/marca-texto-glitter.jpg",
        name: "Marca-texto Flash Glitter",
        brand: 'Tris',
        type: "marca-textos",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/marca-texto-pastel-bic.jpg",
        name: "Marca-texto Pastel C/4",
        brand: 'Bic',
        type: "marca-textos",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/marca-texto-neon-keep.jpg",
        name: "Marca-texto Neon C/4",
        brand: 'Keep',
        type: "marca-textos",
        price: '14.95',
        falta: false,
    },
    //marcador permanente
    {
        img: "./images/pincel-atomico-pilot.webp",
        name: "Pincel Atômico Permanente 1100-P Recarregável",
        brand: 'Pilot',
        type: "marcador-permanente",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/marcador-permanente-pilot-fino.webp",
        name: "Marcador Permanente Retroprojetor 2.0mm Cores",
        brand: 'Pilot',
        type: "marcador-permanente",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/marcador-permanente-keep-preto.webp",
        name: "Marcador Permanente Preto Recaregável Ponta Chanfrada",
        brand: 'Keep',
        type: "marcador-permanente",
        price: '5.00',
        falta: false,
    },
    {
        img: "./images/marcador-permanente-bic-marking.png",
        name: "Marcador Permanente Marking Cores",
        brand: 'Bic',
        type: "marcador-permanente",
        price: '5.00',
        falta: false,
    },
    {
        img: "./images/marcador-permanente-bic-azul.webp",
        name: "Marcador Permanente Azul Reccaregável Ponta Chanfrada",
        brand: 'Keep',
        type: "marcador-permanente",
        price: '5.00',
        falta: false,
    },
    //massa de modelar
    {
        img: "./images/massa-de-modelar-acrilex.webp",
        name: "Massa de Modelar SOFT 180g C/12 Cores",
        brand: 'Acrilex',
        type: "massa-de-modelar",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/massa-de-modelar-koala.jpg",
        name: "Massa de Modelar 120g C/12 Cores",
        brand: 'Koala',
        type: "massa-de-modelar",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/massa-de-modelar-onda.webp",
        name: "Massa de Modelar 180g C/12 Cores",
        brand: 'Onda',
        type: "massa-de-modelar",
        price: '8.95',
        falta: false,
    },
    //papel 180gr
    {
        img: "./images/papel-opaline-usapel.jpg",
        name: "Papel Opaline 180gr 50FL",
        brand: 'Usapel',
        type: "papel-180gr",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/papel-casca-de-ovo.jpg",
        name: "Papel Casca de Ovo 180gr 50FL",
        brand: 'Usapel',
        type: "papel-180gr",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/chamequinho-180gr.webp",
        name: "Papel Sulfite Chamequinho A4 180gr 50FL",
        brand: 'Sylvamo',
        type: "papel-180gr",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/filipaper-premium.webp",
        name: "Papel Filipaper Premium A4 180gr 20FL",
        brand: 'Sylvamo',
        type: "papel-180gr",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/papel-offset-nexel.jpg",
        name: "Papel Offset A4 180gr 50FL",
        brand: 'Nexel',
        type: "papel-180gr",
        price: '24.95',
        falta: false,
    },
    //papel A3
    {
        img: "./images/resma-papel-a3-chamex.webp",
        name: "Resma de Papel Ofício Chamex A3 500FL",
        brand: 'Sylvamo',
        type: "papel-a3",
        price: '69.95',
        falta: false,
    },
    {
        img: "./images/papel-chanson-a3.webp",
        name: "Papel Chanson A3 150GR 20FL",
        brand: 'Romitec',
        type: "papel-a3",
        price: '24.95',
        falta: false,
    },
    //papel carbono
    {
        img: "./images/papel-carbono.png",
        name: "Papel Carbono A4 1 Face Preto 100FL",
        brand: 'Bazze',
        type: "papel-carbono",
        price: '39.95',
        falta: false,
    },
    //papel fotográfico
    {
        img: "./images/papel-foto-nexel-20fl.webp",
        name: "Papel Fotográfico 180gr 20FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '12.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-nexel-50fl.webp",
        name: "Papel Fotográfico 180gr 50FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '25.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-adesivo-nexel-20fl.webp",
        name: "Papel Fotográfico Adesivo 130gr 20FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '18.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-adesivo-nexel-50fl.webp",
        name: "Papel Fotográfico Adesivo 130gr 50FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '35.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-nexel-20fl-120gr.webp",
        name: "Papel Fotográfico 120gr 20FL",
        brand: 'Nexel',
        type: "papel-fotografico",
        price: '10.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-baag-50fl.webp",
        name: "Papel Fotográfico 135gr 50FL",
        brand: 'Baag',
        type: "papel-fotografico",
        price: '25.00',
        falta: false,
    },
    {
        img: "./images/papel-foto-baag-20fl.webp",
        name: "Papel Fotográfico 180gr 20FL",
        brand: 'Baag',
        type: "papel-fotografico",
        price: '12.00',
        falta: false,
    },
    //flip chart
    {
        img: "./images/flip-chart.jpg",
        name: "Flip Chart",
        brand: 'Mademaster',
        type: "flip-chart",
        price: '149.95',
        falta: false,
    },
    {
        img: "./images/papel-para-flip-chart-stalo.webp",
        name: "Papel para Flip Chart 50FL",
        brand: 'Stalo',
        type: "flip-chart",
        price: '79.95',
        falta: false,
    },
    //Papel sulfite
    { 
        img: "./images/resma-papel-chamex.webp",
        name: "Resma de Papel Ofício Chamex A4 500FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '25.00',
        falta: false,
    },
    {
        img: "./images/chamequinho-branco.webp",
        name: "Papel Sulfite 75g Chamequinho Branco A4 100FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/chamequinho-amarelo.webp",
        name: "Papel Sulfite 75g Chamequinho Amarelo A4 100FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/chamequinho-verde.webp",
        name: "Papel Sulfite 75g Chamequinho Verde A4 100FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/chamequinho-rosa.webp",
        name: "Papel Sulfite 75g Chamequinho Rosa A4 100FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/chamequinho-azul.webp",
        name: "Papel Sulfite 75g Chamequinho Azul A4 100FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/chamequinho-colorido.webp",
        name: "Papel Sulfite 75g Chamequinho Colorido A4 100FL",
        brand: 'Sylvamo',
        type: "papel-sulfite",
        price: '9.95',
        falta: false,
    },
    //pasta az
    {
        img: "./images/pasta-az-frama.avif",
        name: "Pasta AZ Ofício Lombo Largo Tigrada",
        brand: 'Frama',
        type: "pasta-az",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/pasta-az-chies.webp",
        name: "Pasta AZ Ofício Lombo Largo Cores",
        brand: 'Chies',
        type: "pasta-az",
        price: '29.95',
        falta: false,
    },
    //pasta catálogo
    {
        img: "./images/pasta-catalogo-carpa-100.webp",
        name: "Pasta Catalógo Preta C/100 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '34.95',
        falta: false,
    },
    {
        img: "./images/pasta-catalogo-carpa-100.webp",
        name: "Pasta Catalógo Preta C/50 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '29.95',
        falta: true,
    },
    {
        img: "./images/pasta-catalogo-carpa-100.webp",
        name: "Pasta Catalógo Preta C/30 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/pasta-catalogo-carpa-100.webp",
        name: "Pasta Catalógo Preta C/10 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/pasta-catalogo-pequena.jpg",
        name: "Pasta Catalógo Preta Pequena C/10 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '11.95',
        falta: false,
    },
    {
        img: "./images/pasta-catalogo-pequena.jpg",
        name: "Pasta Catalógo Preta Pequena C/30 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/pasta-catalogo-pequena.jpg",
        name: "Pasta Catalógo Preta Pequena C/50 Sacos Plásticos",
        brand: 'Carpa',
        type: "pasta-catalogo",
        price: '19.95',
        falta: false,
    },
    //pasta sanfonada
    {
        img: "./images/pasta-sanfonada-31div.jpg",
        name: "Pasta Sanfonada com Elástico C/31 Divisórias",
        brand: 'Pendente',
        type: "pasta-sanfonada",
        price: '69.95',
        falta: false,
    },
    {
        img: "./images/pasta-sanfonada-12div.webp",
        name: "Pasta Sanfonada com Elástico C/12 Divisórias",
        brand: 'Pendente',
        type: "pasta-sanfonada",
        price: '29.95',
        falta: false,
    },
    //pilhas e baterias
    {
        img: "./images/pilha-maxprint-palito-c2.jpg",
        name: "Pilha Alcalina AAA 2un",
        brand: 'Maxprint',
        type: "pilhas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/pilha-philips-pequena.png",
        name: "Pilha Alcalina AA 4un",
        brand: 'Philips',
        type: "pilhas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/bateria-sonic.webp",
        name: "Bateria 9V",
        brand: 'Elgin',
        type: "pilhas",
        price: '14.95',
        falta: false,
    },
    //post-it
    {
        img: "./images/clips-20-ecco-100.webp",
        name: "Post-it Transparente Adesivo Holic C/50FL",  
        brand: 'Tris',
        type: "post-it",
        price: '9.95',
        falta: false,
    },
    //reguas
    {
        img: "./images/escalimetro-maped.jpg",
        name: "Escalímetro",
        brand: 'Maped',
        type: "reguas",
        price: '39.95',
        falta: false,
    },
    {
        img: "./images/regua-de-aluminio.webp",
        name: "Régua de Alumínio 30cm",
        brand: 'Jocar Office',
        type: "reguas",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/regua-flexivel-onda.webp",
        name: "Régua Flexível 30cm",
        brand: 'Onda',
        type: "reguas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/regua-acrilico-waleu.webp",
        name: "Régua Acrílica Cristal 30cm",
        brand: 'Waleu',
        type: "reguas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/kit-geometrico-onda.webp",
        name: "Kit Geométrico C/4 Peças",
        brand: 'Onda',
        type: "reguas",
        price: '3.95',
        falta: false,
    },
    //telas
    {
        img: "./images/tela-20x30.webp",
        name: "Tela Artística 20x30",
        brand: 'Mademaster',
        type: "telas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/tela-30x30.jpg",
        name: "Tela Artística 30x30",
        brand: 'Mademaster',
        type: "telas",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tela-40x50.webp",
        name: "Tela Artística 40x50",
        brand: 'Mademaster',
        type: "telas",
        price: '24.95',
        falta: true,
    },
    //tesouras
    {
        img: "./images/tesoura-de-picotar-leoeleo.webp",
        name: "Tesoura de Picotar Cores",
        brand: 'Leo&Leo',
        type: "tesouras",
        price: '12.95',
        falta: false,
        },
    {
    img: "./images/tesoura-maped-security.jpg",
    name: "Tesoura Escolar Security 12cm",
    brand: 'Maped',
    type: "tesouras",
    price: '9.95',
    falta: false,
    },
    {
        img: "./images/tesoura-maped-soft.jpg",
        name: "Tesoura Escolar Soft 13cm",
        brand: 'Maped',
        type: "tesouras",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/tesoura-escolar-onda.jpg",
        name: "Tesoura Escolar 13cm Cores",
        brand: 'Onda',
        type: "tesouras",
        price: '4.95',
        falta: false,
    },
    {
        img: "./images/tesoura-912.webp",
        name: "Tesoura Color 9 1/2",
        brand: 'Original Line',
        type: "tesouras",
        price: '19.95',
        falta: false,
    },
    //tintas
    {
        img: "./images/pintura-a-dedo-pira-15ml.webp",
        name: "Pintura a Dedo 15ml C/6 Cores",
        brand: 'Piratininga',
        type: "tintas",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/tinta-3d-amarela.jpg",
        name: "Tinta 3D Amarela 35ml",
        brand: 'Acrilex',
        type: "tintas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/tinta-3d-azul.jpg",
        name: "Tinta 3D Azul Turquesa 35ml",
        brand: 'Acrilex',
        type: "tintas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/aquarela-onda.jpg",
        name: "Estojo de Tinta Aquarela 12 cores + Pincel",
        brand: 'Onda',
        type: "tintas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/tinta-guache-koala-250ml.webp",
        name: "Tinta Guache Escolar 250ml Cores",
        brand: 'Koala',
        type: "tintas",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/tinta-guache-pira-250ml.jpeg",
        name: "Tinta Guache Escolar 250ml Cores",
        brand: 'Piratininga',
        type: "tintas",
        price: '7.95',
        falta: false,
    },
    {
        img: "./images/tinta-guache-caixinha.webp",
        name: "Tinta Guache Escolar 15ml C/6",
        brand: 'Piratininga',
        type: "tintas",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/tinta-para-tecido-acrilex.webp",
        name: "Tinta para Tecido 37ml",
        brand: 'Acrilex',
        type: "tintas",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-544-preta.webp",
        name: "Tintas para impressora Epson 544 Preta 70ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-544-rosa.jpg",
        name: "Tintas para impressora Epson 504/544 Magenta 70ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-544-amarela.jpg",
        name: "Tintas para impressora Epson 504/544 Amarela 70ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-544-azul.jpg",
        name: "Tintas para impressora Epson 544 Ciano 70ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-504-127ml.jpg",
        name: "Tinta para impressora Epson 504 Preta 127ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-664-azul.jpg",
        name: "Tintas para impressora Epson 664 Ciano 100ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-664-rosa.jpg",
        name: "Tintas para impressora Epson 664 Magenta 100ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },  
    {
        img: "./images/tinta-imp-664-amarela.jpg",
        name: "Tintas para impressora Epson 664 Amarela 100ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    {
        img: "./images/tinta-imp-664-preta.jpg",
        name: "Tintas para impressora Epson 664 Preta 100ml",
        brand: 'Nexel',
        type: "tintas-imp",
        price: '12.95',
        falta: false,
    },
    //variados
    {
        img: "./images/lupa.jpg",
        name: "Lupa anti-deformação 5X 45mm",
        brand: 'Cis',
        type: "lupas",
        price: '24.95',
        falta: false,
    },
    {
        img: "./images/papel-madeira.webp",
        name: "Folha de Papel Madeira Kraft",
        brand: 'Pendente',
        type: "variados",
        price: '2.00',
        falta: false,
    },
    {
        img: "./images/lampada-elgin.webp",
        name: "Lâmpada Bulbo 9W 6500K",
        brand: 'Elgin',
        type: "variados",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/acendedor-bic.webp",
        name: "Acendedor Handy Azul Recarregável com Isqueiro",
        brand: 'Bic',
        type: "variados",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/espeto-madeira-theoto.jpg",
        name: "Espeto de Madeira Grande C/100",
        brand: 'Theoto',
        type: "variados",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/papel-pautado.jpg",
        name: "Papel Almaço/Pautado C/10",
        brand: 'Pendente',
        type: "variados",
        price: '2.00',
        falta: false,
    },
    {
        img: "./images/palito-picole-vermelho.webp",
        name: "Palito de Picolé Ponta Redonda Vermelho C/100",
        brand: 'Theoto',
        type: "variados",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/palito-picole-azul.webp",
        name: "Palito de Picolé Ponta Redonda Azul C/100",
        brand: 'Theoto',
        type: "variados",
        price: '9.95',
        falta: false,
    },
]
