// todos os dados de produtos existentes
const data = [
    //agendas
    {
        img: "./images/agenda-pepper.webp",
        name: "Agenda Costurada Pepper M4 160fls 2023",
        brand: 'Tilibra',
        type: "agendas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/agenda-pratika-master.webp",
        name: "Agenda Costurada Pratika Master M4 176fls 2023",
        brand: 'Tilibra',
        type: "agendas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/agenda-napoli.webp",
        name: "Agenda Costurada Napoli M5 176fls 2023",
        brand: 'Tilibra',
        type: "agendas",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/agenda-infantil.jpg",
        name: "Agenda Escolar Infantil 96fls",
        brand: 'Foroni',
        type: "agendas",
        price: '14.95',
        falta: false,
    },
    {
        img: "./images/agenda-espiral-d+.jfif",
        name: "Agenda Espiral Diária D+ 2023",
        brand: 'Tilibra',
        type: "agendas",
        price: '19.95',
        falta: false,
    },
    
    //apagadores
    {
        img: "./images/apagador-para-quadro-branco.webp",
        name: "Apagador para quadro branco preto",
        brand: 'Radex',
        type: "apagadores-para-quadro",
        price: '11.95',
        falta: false,
    },
    {
        img: "./images/apagador-formato-mouse.jpg",
        name: "Apagador magnético para quadro branco em formato de mouse",
        brand: 'Radex',
        type: "apagadores-para-quadro",
        price: '19.95',
        falta: false,
    },
    {
        img: "./images/limpador-de-quadro-branco.webp",
        name: "Limpador de quadro branco spray",
        brand: 'Radex',
        type: "apagadores-para-quadro",
        price: '24.95',
        falta: false,
    },
    //apontadores
    {
        img: "./images/apontador-metal-onda.webp",
        name: "Apontador de metal",
        brand: 'Onda',
        type: "apontadores",
        price: '1.95',
        falta: false,
    },
    {
        img: "./images/apontador-plástico-pequeno.jpg",
        name: "Apontador depósito de plástico",
        brand: 'Onda',
        type: "apontadores",
        price: 'XX',
        falta: false,
    },
    {
        img: "./images/apontador-oval-onda.jpg",
        name: "Apontador depósito oval de plástico",
        brand: 'Onda',
        type: "apontadores",
        price: 'XX',
        falta: false,
    },
    {
        img: "./images/apontador-batman.webp",
        name: "Apontador batman",
        brand: 'Tris',
        type: "apontadores",
        price: 'XX',
        falta: false,
    },
    {
        img: "./images/apontador-barbie.webp",
        name: "Apontador barbie",
        brand: 'Tris',
        type: "apontadores",
        price: 'XX',
        falta: false,
    },
    {
        img: "./images/apontador-naruto.webp",
        name: "Apontador naruto",
        brand: 'Tris',
        type: "apontadores",
        price: 'XX',
        falta: false,
    },
    //aquarela 
    {
        img: "./images/aquarela-onda.jpg",
        name: "Estojo tinta aquarela 12 cores + pincel",
        brand: 'Onda',
        type: "aquarela",
        price: '11.95',
        falta: false,
    },
    //bobinas
    {
        img: "./images/bobina-80-40-48.webp",
        name: "Bobina 80mm x 40m x 48g",
        brand: 'Silfer',
        type: "bobinas",
        price: '6.95',
        falta: false,
    },
    {
        img: "./images/bobina-57-22.webp",
        name: "Bobina 57mm x 22m",
        brand: 'Rio branco',
        type: "bobinas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/bobina-57-300-48.webp",
        name: "Bobina 57mm x 300m x 48g",
        brand: 'Rio branco',
        type: "bobinas",
        price: '44.95',
        falta: false,
    },
    {
        img: "./images/bobina-57-30.jpg",
        name: "Bobina 57mm x 30m",
        brand: 'Silfer',
        type: "bobinas",
        price: '3.95',
        falta: false,
    },
    //borrachas
    {
        img: "./images/borracha-redbor.webp",
        name: "Borracha Bicolor AV40",
        brand: 'Red-bor',
        type: "borrachas",
        price: '1.95',
        falta: false,
    },
    {
        img: "./images/borracha-leoeleo.webp",
        name: "Borracha Colorida",
        brand: 'Leo & Leo',
        type: "borrachas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/borracha-bic.webp",
        name: "Borracha Branca com capa",
        brand: 'Bic',
        type: "borrachas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/borracha-onda.webp",
        name: "Borracha Neon com capa",
        brand: 'Onda',
        type: "borrachas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/borracha-neon-brw.webp",
        name: "Borracha Neon com capa",
        brand: 'Brw',
        type: "borrachas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/borracha-faber-glitz.webp",
        name: "Borracha Max Glitz",
        brand: 'Fabber-Castell',
        type: "borrachas",
        price: '5.95',
        falta: false,
    },
    {
        img: "./images/borracha-maped-shakky.webp",
        name: "Borracha Shakky Bichinhos 2 unidades",
        brand: 'Maped',
        type: "borrachas",
        price: '9.95',
        falta: false,
    },
    {
        img: "./images/borracha-branca-leoeleo.jpg",
        name: "Borracha branca com capa verde",
        brand: 'Leo & Leo',
        type: "borrachas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/borracha-mercur-big.webp",
        name: "Borracha Branca Big com capa preta",
        brand: 'Mercur',
        type: "borrachas",
        price: '5.95',
        falta: false,
    },
    //calculadoras
    {
        img: "./images/calculadora-brw.jpg",
        name: "Calculadora eletrônica de mesa 12 dígitos",
        brand: 'Brw',
        type: "calculadoras",
        price: '29.95',
        falta: false,
    },
    //canetas
    {
        img: "./images/caneta-bic-cristal.webp",
        name: "Caneta Bic Cristal 1.0mm",
        brand: 'Bic',
        type: "canetas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-fine.webp",
        name: "Caneta Bic Fine 0.8mm",
        brand: 'Bic',
        type: "canetas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-compactor.webp",
        name: "Caneta Compactor 0.7mm",
        brand: 'Compactor',
        type: "canetas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-fabber.webp",
        name: "Caneta Fabber-Castell 1.0mm",
        brand: 'Fabber',
        type: "canetas",
        price: '1.50',
        falta: false,
    },
    {
        img: "./images/caneta-bic-bold.webp",
        name: "Caneta Bic Bold Intenso 1.6mm",
        brand: 'Bic',
        type: "canetas",
        price: '2.95',
        falta: false,
    },
    {
        img: "./images/caneta-bic-ultrafine.webp",
        name: "Caneta Bic Ultra Fine 0.7mm",
        brand: 'Bic',
        type: "canetas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-spiro.webp",
        name: "Caneta Cis Spiro 0.7mm",
        brand: 'Cis',
        type: "canetas",
        price: '3.95',
        falta: false,
    },
    {
        img: "./images/caneta-pilot-bp-1.webp",
        name: "Caneta Pilot BP-1",
        brand: 'Pilot',
        type: "canetas",
        price: '3.95',
        falta: false,
    },
    //compassos
    {
        img: "./images/compasso-tris.jfif",
        name: "Compasso escolar SU123",
        brand: 'Tris',
        type: "compassos",
        price: '11.95',
        falta: false,
    },
    {
        img: "./images/compasso-onda.webp",
        name: "Compasso escolar metal",
        brand: 'Onda',
        type: "compassos",
        price: '9.95',
        falta: false,
    },
    //mouses
    {
        img: "./images/mouse-sem-fio.webp",
        name: "Mouse sem fio 1200dpi",
        brand: 'Multilaser',
        type: "mouses",
        price: '39.95',
        falta: false,
    },
    //mouse pads
    {
        img: "./images/mouse-pad-multilaser-slim.webp",
        name: "Mouse pad slim",
        brand: 'Multilaser',
        type: "mouse-pads",
        price: '8.95',
        falta: false,
    },
    {
        img: "./images/mouse-pad-multilaser-ergonomico.webp",
        name: "Mouse pad ergonômico com apoio gel",
        brand: 'Multilaser',
        type: "mouse-pads",
        price: '39.95',
        falta: false,
    },
    
    //perfuradores
    {
        img: "./images/perfurador-alicate-brw.webp",
        name: "Perfurador de papel alicate metálico",
        brand: 'Brw',
        type: "perfuradores",
        price: '14.95',
        falta: false,
    },
    //pilhas e baterias
    {
        img: "./images/bateria-sonic.webp",
        name: "Bateria 9V",
        brand: 'Elgin',
        type: "pilhas",
        price: '14.95',
        falta: false,
    },
    //teclados
    {
        img: "./images/teclado-multilaser.webp",
        name: "Teclado Básico com fio USB",
        brand: 'Multilaser',
        type: "teclados",
        price: '49.95',
        falta: false,
    },
]
